/* eslint-disable */
module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.ts', '**/__tests__/**/*.test.tsx'],
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^react-native$': '<rootDir>/src/__mocks__/react-native.ts',
    '^react-native-keychain$': '<rootDir>/src/__mocks__/react-native-keychain.ts',
    '^react-native-image-picker$': '<rootDir>/src/__mocks__/react-native-image-picker.ts',
    '^react-native-image-resizer$': '<rootDir>/src/__mocks__/react-native-image-resizer.ts',
    '^@react-native-community/netinfo$': '<rootDir>/src/__mocks__/@react-native-community/netinfo.ts',
    '^expo-constants$': '<rootDir>/src/__mocks__/expo-constants.ts',
    '^expo-sqlite$': '<rootDir>/src/__mocks__/expo-sqlite.ts',
    '^expo-notifications$': '<rootDir>/src/__mocks__/expo-notifications.ts',
    '^expo-secure-store$': '<rootDir>/src/__mocks__/expo-secure-store.ts',
    '^expo-file-system$': '<rootDir>/src/__mocks__/expo-file-system.ts',
    '^expo-sharing$': '<rootDir>/src/__mocks__/expo-sharing.ts',
    '^expo-local-authentication$': '<rootDir>/src/__mocks__/expo-local-authentication.ts',
    '^qrcode$': '<rootDir>/src/__mocks__/qrcode.js',
    '^@sentry/react-native$': '<rootDir>/src/__mocks__/@sentry/react-native.ts',
    '^pg$': '<rootDir>/src/__mocks__/pg.js',
    '^@elastic/elasticsearch$': '<rootDir>/src/__mocks__/@elastic/elasticsearch.js',
    '^socket\\.io$': '<rootDir>/src/__mocks__/socket.io.js',
    '^socket\\.io-client$': '<rootDir>/src/__mocks__/socket.io-client.js',
    '^sharp$': '<rootDir>/src/__mocks__/sharp.js',
    '^multer$': '<rootDir>/src/__mocks__/multer.js',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx',
    'backend/**/*.ts',
    '!src/**/__tests__/**',
    '!src/**/__mocks__/**',
    '!backend/**/__tests__/**',
    '!**/node_modules/**',
    '!**/dist/**',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  testTimeout: 10000,
  verbose: true,
};
